#!/bin/bash

# Executes a command, but sends a notification to the user
# wall - Write all users

# Features:
# 	Always write a notification when programs are being run (always done)
#	Log results of program and timestamps into a logfile (always done, will need something to occasionally clear this out) @TODO
# 	Write to a file to send to the phone (-w)
# 	Speak the results using espeak, or just speak recieved text (-s)

# https://stackoverflow.com/questions/192249/how-do-i-parse-command-line-arguments-in-bash
CMD=""
SPEAK="0"
SEND="0"
MUTE="0"

TMPDIR="/tmp/kdeconnect_$(whoami)/" # Temporary Directory to dump files in
LOGFILE="${HOME}/log/mch.log"

mkdir -p $TMPDIR

for i in "$@"
do
case $i in 
	-s|--speak)
	SPEAK=1
	;;
	-w|--send)
	SEND=1
	;;
	-m|--mute)
	MUTE=1
	;;
	*)
	CMD="$CMD ${i#}"
esac
done

OUTPUT=$($CMD 2>&1) # Executes the code here, also send stderr too!

# Write notification to all users, only if not muted
if [ $MUTE -eq "0" ]; then
	wall "$(whoami) $> $CMD :--> $OUTPUT"
fi

# Log the command and result.
echo "$(date)","$(whoami)","\"$CMD\"","\"$OUTPUT\"" >> "$LOGFILE"

if [ $SPEAK -eq "1" ]; then
	espeak "$OUTPUT" &
fi

if [ $SEND -eq "1" ]; then
	FNAME=$(date +%s) # Unique Name as time in seconds since 1970
	echo "$OUTPUT" > $TMPDIR$FNAME.txt
	cat "$TMPDIR$FNAME.txt"
	kdeconnect-cli -a --id-only | xargs -I {} kdeconnect-cli -d {} --share $TMPDIR$FNAME.txt
fi
